defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "blog/*"
    values:
      layout: "default"

plugins: [jekyll-paginate]    
paginate: 5
paginate_path: "/blog/page:num/"

website: http://localhost:4000
basewebsite: 
permalink: date